apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Virtual Service para transición entre Microservicios
  description: |
    Este blueprint crea una versión de Virtual Service para transición de microservicios.
  author: JC
  version: 1.0
parameters:
# Applications
- name: ApplicationName
  description: Nombre de la aplicación al que pertenece el microservicio
  type: Select
  options:
    - voting-app
    - moby-counter
    - calculator
    - petclinic
- name: MicroserviceName
  description: Nombre del microservicio
  type: Select
  options:
    - vote
    - result
    - redis
    - db
    - worker
- name: MicroserviceVersion1
  description: Versión del microservicio a sustituir
  type: Input
  default: 32.0.0-B40
- name: MicroserviceVersion2
  description: Versión del microservicio a instalar
  type: Input
  default: 32.0.0-B41
- name: ServicePort1
  description: Puerto expuesto por el servicio a sustituir
  type: Input
  default: 5000
- name: ServicePort2
  description: Puerto expuesto por el servicio a instalar
  type: Input
  default: 5000

files:
- path: xebialabs/resourcesFiles/virtual-service.yaml.tmpl
- path: xebialabs/virtual-service.yaml.tmpl
- path: xebialabs.yaml.tmpl
