apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Microservicios
  description: |
    Este blueprint crea varias aplicaciones con distintos componentes K8S.
    Crea tambien los distintos recursos para que puedan ser gestionados por Istio.
  author: JC
  version: 1.0
parameters:
# Applications
- name: ApplicationName
  description: Nombre de la aplicación al que pertenece el microservicio
  type: Select
  options:
    - voting-app
    - moby-counter
    - calculator
    - petclinic
- name: MicroserviceName
  description: Nombre del microservicio
  type: Select
  options:
    - vote
    - result
    - redis
    - db
    - worker
- name: MicroserviceVersion
  description: Versión del microservicio
  type: Input
  default: 32.0.0-B40
- name: ContainerPort
  description: Puerto expuesto por el contenedor
  type: Input
  default: 80
- name: ServicePort
  description: Puerto expuesto por el servicio
  type: Input
  default: 5000

files:
- path: xebialabs/deployment.yaml.tmpl
- path: xebialabs/service.yaml.tmpl
- path: xebialabs/resourcesFiles/destination-rules.yaml.tmpl
- path: xebialabs/destination-rules.yaml.tmpl
- path: xebialabs.yaml.tmpl
