apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Java War
  description: |
    Este blueprint crea una aplicación con un único componente de tipo jee.War.
    También incluye un smoke test para validar que el despliegue se hizo de forma correcta.
  author: JC
  version: 1.0
parameters:
- name: AppFolder
  description: ¿En qué directorio se ubicará la aplicación?
  type: Select
  options:
    - Java/Front
    - Java/Back
    - Java/Library
  default: Java/Front
- name: AppName
  description: ¿Cuál es el nombre de la aplicación?
  type: Input
  default: HelloWorld
- name: AppVersion
  description: ¿Cuál es la versión de la aplicación a crear?
  type: Input
  default: 1.0.0-B1

files:
- path: xebialabs/application.yaml.tmpl
- path: xebialabs.yaml
