apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Microservicios
  description: |
    This blueprint creates several aplications with diferent resources for K8S.
    It also creates several resources so it can be managed by Istio.
  author: JC
  version: 1.0
parameters:
# Applications
- name: ApplicationName
  description: Name of the application to which the microservice belongs
  type: Select
  options:
    - voting-app
    - moby-counter
    - calculator
    - petclinic
- name: MicroserviceName
  description: Name of the microservice
  type: Select
  options:
    - vote
    - result
    - redis
    - db
    - worker
- name: MicroserviceVersion
  description: Version of the microservice
  type: Input
  default: 32.0.0-B41
- name: ContainerPort
  description: Port exposed by the container
  type: Input
  default: 80
- name: ServicePort
  description: Port exposed by the service
  type: Input
  default: 5000
- name: GenerateTransition
  description: Are you updating an existing version of this microservice?
  type: Select
  options:
    - "Yes"
    - "No"
- name: MicroserviceVersionToReplace
  description: Version of the microservice to replace
  type: Input
  default: 32.0.0-B40
  dependsOnTrue: !expression GenerateTransition == 'Yes'

files:
- path: xebialabs/deployment.yaml.tmpl
- path: xebialabs/service.yaml.tmpl
- path: xebialabs/resourcesFiles/destination-rules.yaml.tmpl
- path: xebialabs/resourcesFiles/virtual-service.yaml.tmpl
- path: xebialabs/resourcesFiles/virtual-service-transition.yaml.tmpl
  dependsOnTrue: !expression GenerateTransition == 'Yes'
- path: xebialabs/resourcesFiles/gateway-istio.yaml.tmpl
- path: xebialabs/virtual-service.yaml.tmpl
- path: xebialabs/gateway.yaml.tmpl
- path: xebialabs/virtual-service-transition.yaml.tmpl
  dependsOnTrue: !expression GenerateTransition == 'Yes'
- path: xebialabs.yaml.tmpl
